---
####################################################
# Operators
####################################################
# 1: # idf
idf_damage: 30
idf_health: 150
idf_velocity: 20
idf_rate: 20
idf_capacity: 50
idf_injure: 3
idf_reload_time: 2
idf_rate_time: 0.05
idf_burst_delay: 0.1

# 2: # p90
p90_damage: 20
p90_health: 140
p90_velocity: 30
p90_rate: 10
p90_capacity: 30
p90_injure: 3
p90_reload_time: 1
p90_rate_time: 0.05
p90_burst_delay: 0.15

# 3: # scout
scout_damage: 60
scout_health: 200
scout_velocity: 12
scout_rate: 1
scout_capacity: 20
scout_injure: 3
scout_reload_time: 1.5
scout_rate_time: 0.4
scout_burst_delay: 0.25

# skills:
stop_skill_time: 1
#   grenade:
grenade_damage: 50
grenade_recharge: 10

#   smoke:
smoke_damage: 0
smoke_recharge: 10

#   blitz:
blitz_damage: 100
blitz_recharge: 30
blitz_animation_time: 1.7

####################################################
# Infected
####################################################
# Zombie
zombie_damage: 5
zombie_health: 80
zombie_velocity: 15

# Jumper
jumper_damage: 15
jumper_health: 120
jumper_velocity: 30

# Witch
witch_damage: 50
witch_health: 900
witch_velocity: 40

# Spear
spear_damage: 30
spear_health: 200
spear_velocity: 20

# Venom
venom_damage: 25
venom_health: 180
venom_velocity: 20

####################################################
# Game Difficulty
####################################################
# Easy
zombie_amount_easy: 10
jumper_amount_easy: 3
witch_amount_easy: 2
spear_amount_easy: 4
venom_amount_easy: 2

# Normal
zombie_amount_normal: 20
jumper_amount_normal: 6
witch_amount_normal: 4
spear_amount_normal: 7
venom_amount_normal: 5

# Hard
zombie_amount_hard: 30
jumper_amount_hard: 10
witch_amount_hard: 6
spear_amount_hard: 11
venom_amount_hard: 9

# God
zombie_amount_god: 50
jumper_amount_god: 20
witch_amount_god: 10
spear_amount_god: 15
venom_amount_god: 15