---
idf_damage: 30
idf_health: 150
idf_velocity: 15
idf_rate: 20
idf_capacity: 50
idf_injure: 3
# 2: # p90
p90_damage: 20
p90_health: 140
p90_velocity: 20
p90_rate: 10
p90_capacity: 30
p90_injure: 3
# 3: # scout
scout_damage: 60
scout_health: 200
scout_velocity: 8
scout_rate: 1
scout_capacity: 20
scout_injure: 3

# skills:
#   grenade:
grenade_damage: 50
grenade_recharge: 10
#   smoke:
smoke_damage: 0
smoke_recharge: 10
#   blitz:
blitz_damage: 100
blitz_recharge: 30


